package com.sample
 
import com.sample.Message;
import org.drools.core.common.EventFactHandle;
import org.drools.core.base.DefaultKnowledgeHelper;

import java.util.Date;


declare Message
    @role( event )
    @expires(1000d)
end


rule "Is there any close message?"
    when
        $m1 : Message( )
        not (Message( this != $m1, this after[0, 50d] $m1 ))
    then
        System.out.println( "fired");
end
