package com.sample

import com.sample.Person;

rule Hello1
  salience 100
  activation-group "groupA"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello1, " + $p.getName());
end

rule Hello2
  salience 100
  activation-group "groupA"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello2, " + $p.getName());
end

rule Hello3
  salience 50
  activation-group "groupA"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello3, " + $p.getName());
end
