package com.sample

import com.sample.Person;

// in sequential mode, update doesn't affect rule which are already evaluated. So the order (or salience) of rules matters

rule Hello2
  //salience 10
  when
    $p : Person(age >= 18)
  then
    System.out.println("Hello adult, " + $p.getName());
end



rule Hello1
  //salience 20
  when
    $p : Person(age < 18)
  then
    System.out.println("Hello child, " + $p.getName());
    $p.setAge(18);
    update($p);
end

