package com.sample
 
import com.sample.Message;

import org.drools.core.common.EventFactHandle;

import org.drools.core.base.DefaultKnowledgeHelper;

declare Message
    @role( event )
    //@timestamp( messageDate )
end


rule "Is there any close message?"
    when
        $m1 : Message( )
        $m2 : Message( this != $m1 && this after[0, 50d] $m1 )
    then
        System.out.println( $m1 + " and " + $m2 + " are close");
        EventFactHandle handle = (EventFactHandle)((DefaultKnowledgeHelper)kcontext).getFactHandle($m2);
        System.out.println(handle.getStartTimestamp());
end
