package com.sample

import com.sample.Customer;
import com.sample.Order;
import java.util.ArrayList;

global java.util.List result;

rule "Collect expensive orders combination"
  when
    $c : Customer()
    $o1 : Order(customer == $c)
    $o2 : Order(customer == $c, id > $o1.id, price > $o1.price)
    $maxPrice : Integer() from accumulate (Order(customer == $c, $price : price), max($price))
    eval($o1.getPrice() > ($maxPrice - 50))
  then
    ArrayList<Order> combination = new ArrayList<>();
    combination.add($o1);
    combination.add($o2);
    result.add(combination);
end