package com.sample
 
import com.sample.Person;
 
rule "Hello"
    when
        $p : Person( age > 20 )
    then
        System.out.println( "Hello, " + $p.getName());
        insertLogical("Hi");
end

rule R1
  when
    $s : String()
  then
    System.out.println($s);
end

rule R2
  when
    $s : String()
  then
    System.out.println($s);
end

rule R3
  when
    $s : String()
  then
    System.out.println($s);
end

rule R4
  when
    $s : String()
  then
    System.out.println($s);
end

rule R5
  when
    $s : String()
  then
    System.out.println($s);
end

rule R6
  when
    $s : String()
  then
    System.out.println($s);
end

rule R7
  when
    $s : String()
  then
    System.out.println($s);
end

rule R8
  when
    $s : String()
  then
    System.out.println($s);
end

rule R9
  when
    $s : String()
  then
    System.out.println($s);
end

rule R10
  when
    $s : String()
  then
    System.out.println($s);
end
