package com.sample

import com.sample.Person;

rule "Row 1 my-decision-table"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello1, " + $p.getName());
end

rule "Row 2 my-decision-table"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello2, " + $p.getName());
end

rule "Row 1 new-decision-table"
  when
    $p : Person(age > 20)
  then
    System.out.println("Hello new1, " + $p.getName());
end